// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMusicAppAPI.Database;

namespace MyMusicAppAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211124173541_context")]
    partial class context
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MyMusicAppAPI.Database.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dance"
                        });
                });

            modelBuilder.Entity("MyMusicAppAPI.Database.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntredDAte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SongUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFavourite")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistName = "Eminem",
                            CategoryID = 1,
                            EditDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1990),
                            EntredDAte = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1990),
                            Name = "Lose Yourself",
                            Rating = 5,
                            SongUrl = "https://www.youtube.com/watch?v=_Yhyp-_hX2s",
                            isFavourite = true
                        },
                        new
                        {
                            Id = 2,
                            ArtistName = "50 Cent",
                            CategoryID = 1,
                            EditDate = new DateTime(2021, 8, 2, 9, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2021, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "In Da Club",
                            Rating = 3,
                            SongUrl = "https://www.youtube.com/watch?v=5qm8PH4xAss",
                            isFavourite = true
                        },
                        new
                        {
                            Id = 3,
                            ArtistName = "The Rolling Stones",
                            CategoryID = 3,
                            EditDate = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "Paint It, Black",
                            Rating = 5,
                            SongUrl = "https://www.youtube.com/watch?v=O4irXQhgMqg",
                            isFavourite = false
                        },
                        new
                        {
                            Id = 4,
                            ArtistName = "The Rolling Stones",
                            CategoryID = 3,
                            EditDate = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2008, 5, 1, 8, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "Miss You",
                            Rating = 5,
                            SongUrl = "https://www.youtube.com/watch?v=KuRxXRuAz-I",
                            isFavourite = false
                        },
                        new
                        {
                            Id = 5,
                            ArtistName = "Stromae",
                            CategoryID = 4,
                            EditDate = new DateTime(2020, 1, 3, 5, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2012, 2, 2, 1, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "Alors On Danse",
                            Rating = 3,
                            SongUrl = "https://www.youtube.com/watch?v=VHoT4N43jK8",
                            isFavourite = true
                        },
                        new
                        {
                            Id = 6,
                            ArtistName = "Freddy Cole",
                            CategoryID = 2,
                            EditDate = new DateTime(2021, 5, 3, 2, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2021, 5, 3, 2, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "This Time I'm Gone for Good",
                            Rating = 5,
                            SongUrl = "https://www.youtube.com/watch?v=5lrSdW8p4u4",
                            isFavourite = true
                        },
                        new
                        {
                            Id = 7,
                            ArtistName = "The White Buffalo",
                            CategoryID = 2,
                            EditDate = new DateTime(2021, 5, 3, 2, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2021, 5, 3, 2, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "House of the Rising Sun",
                            Rating = 3,
                            SongUrl = "https://www.youtube.com/watch?v=MOqm0qGJhpw",
                            isFavourite = false
                        },
                        new
                        {
                            Id = 8,
                            ArtistName = "Eminem",
                            CategoryID = 1,
                            EditDate = new DateTime(2021, 4, 3, 4, 30, 52, 0, DateTimeKind.Unspecified),
                            EntredDAte = new DateTime(2021, 5, 3, 2, 30, 52, 0, DateTimeKind.Unspecified),
                            Name = "Not Afraid",
                            Rating = 3,
                            SongUrl = "https://www.youtube.com/watch?v=j5-yKhDd64s",
                            isFavourite = false
                        });
                });

            modelBuilder.Entity("MyMusicAppAPI.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MyMusicAppAPI.Database.Song", b =>
                {
                    b.HasOne("MyMusicAppAPI.Database.Category", "Category")
                        .WithMany("Songs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyMusicAppAPI.Database.Category", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
